---
- hosts: all
  become: true
  

  tasks:
    - name: Install required packages
      apt: 
        name: ['bind9', 'dstat', 'vim', 'screen', 'fail2ban']
        state: present
        update_cache: yes

    - name: Configure Network interfaces
      template: src=templates/netplan/netcfg.yaml dest=/etc/netplan/01-netcfg.yaml
      register: new_network_config

    - name: Apply networking config
      command: netplan apply
      when: new_network_config.changed

    - name: Configure BIND - Options
      template: src=templates/bind/named.conf.options dest=/etc/bind/named.conf.options
      register: new_bind_config

    - name: Configure BIND - Zones
      template: src=templates/bind/named.conf.local dest=/etc/bind/named.conf.local
      register: new_bind_config

    - name: Configure BIND - Install Empty Direct Delegation Zone File
      template: src=templates/bind/db.dd-empty dest=/etc/bind/db.dd-empty
      register: new_bind_config

    - name: Configure BIND - Install Empty DNAME Redelegation Zone File
      template: src=templates/bind/db.dr-empty dest=/etc/bind/db.dr-empty
      register: new_bind_config

    - name: Configure BIND - Install hostname.as112.net Zone
      template: src=templates/bind/db.hostname.as112.net dest=/etc/bind/db.hostname.as112.net
      register: new_bind_config

    - name: Configure BIND - Install hostname.as112.arpa Zone
      template: src=templates/bind/db.hostname.as112.arpa dest=/etc/bind/db.hostname.as112.arpa
      register: new_bind_config

    - name: Reloading BIND Service
      service:
        name: bind9
        state: reloaded
      when: new_bind_config.changed
